// Session & nav
const sections = ["view-login","view-ordenes","view-usuarios","view-reportes","view-config"];
const navBtns = document.querySelectorAll(".nav-btn");
function show(v){ sections.forEach(id=>document.getElementById(id)?.classList.add("hide")); document.getElementById(v)?.classList.remove("hide"); navBtns.forEach(b=>b.classList.toggle("active", b.dataset.view===v)); const map={"view-login":"Iniciar sesión","view-ordenes":"Órdenes","view-usuarios":"Usuarios","view-reportes":"Reportes","view-config":"Configuración"}; document.getElementById("topTitle").textContent = map[v] || "Panel"; }
navBtns.forEach(b=>b.addEventListener("click",()=>{ const v=b.dataset.view; if(v) show(v); }));
document.getElementById("btnLogout").addEventListener("click",()=>{ session=null; document.getElementById("sessionInfo").textContent="Sin sesión"; show("view-login"); });
let session = null;
function guardByRole(){ const canCreate = session && (session.rol==="superadmin" || session.rol==="admin"); document.getElementById("btnNueva").disabled = !canCreate; }
document.getElementById("btnPing").addEventListener("click", async ()=>{ const el=document.getElementById("loginStatus"); try{ const r=await fetch("/api/test"); const j=await r.json(); el.textContent = j.ok ? ("Conexión OK. GAS_URL "+(j.env.GAS_URL_present?"presente":"faltante")) : "Fallo test"; el.className = "status "+(j.ok?"ok":"err"); }catch(e){ el.textContent=e.message; el.className="status err"; } });
document.getElementById("btnLogin").addEventListener("click", async ()=>{ const usuario=document.getElementById("lUsuario").value.trim(); const clave=document.getElementById("lClave").value; const el=document.getElementById("loginStatus"); try{ const res=await fetch("/api/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({usuario,clave})}); const d=await res.json(); if(!res.ok||d.status!=="ok") throw new Error(d.message||"Error login"); session=d.data; document.getElementById("sessionInfo").textContent = session.usuario+" · "+session.rol; el.textContent = "Sesión iniciada como "+session.usuario+" ("+session.rol+")"; el.className="status ok"; show("view-ordenes"); guardByRole(); }catch(e){ el.textContent=e.message; el.className="status err"; } });